name: Demo - create user dir

on: 
  workflow_dispatch:
    inputs:
      user_id:
        description: The user id for which the name is desired
        required: true
        type: choice
        options: ['1', '2', '3', '4', '5']

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - uses: Safarveisi/custom-github-action@v3
        id: create-user-directory
        with:
          user_id: ${{ github.event.inputs.user_id }}

      - run: |
          echo "Name of the created dir: ${{ steps.create-user-directory.outputs.created_dir }}"
          echo "Also workspace tree looks like this:"
          tree -L 2
