name: Demo - create user dir

on: [workflow_dispatch]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Install dependencies and build dist/ directory
        working-directory: ./custom
        run: |
          npm i & npm run build
      
      - uses: ./custom/
        id: create-user-directory
        with:
          user_id: 3

      - run: |
          echo "Name of the created dir: ${{ steps.create-user-directory.outputs.created_dir }}"
          echo "Also workspace tree looks like this:"
          tree -L 2