name: Demo - create user dir

on: [workflow_dispatch]

jobs:
  demo:
    strategy:
      matrix:
        ids: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install dependencies and build dist/ directory
        run: |
          npm i && npm run build
      
      - uses: ./
        id: create-user-directory
        with:
          user_id: ${{ matrix.ids }}

      - run: |
          echo "Name of the created dir: ${{ steps.create-user-directory.outputs.created_dir }}"
          echo "Also workspace tree looks like this:"
          tree -L 2