name: Demo - create user dir

on: 
  workflow_dispatch:
    inputs:
      user_id:
        description: The user id for which the name is desired
        required: true
        type: choice
        options: ['1', '2', '3', '4', '5']

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '22.17.0'
      #     cache: 'npm'
      #     cache-dependency-path: package-lock.json

      # - name: Install dependencies
      #   run: npm ci 

      # - name:  Build dist/ directory
      #   run: npm run build
      
      - uses: Safarveisi/custom-github-action@v1
        id: create-user-directory
        with:
          user_id: ${{ github.event.inputs.user_id }}

      - run: |
          echo "Name of the created dir: ${{ steps.create-user-directory.outputs.created_dir }}"
          echo "Also workspace tree looks like this:"
          tree -L 2